### ISSUE TITLE
use/include do not need to end with a semi-colon

### ISSUE THREAD

**Issue by mjparme** [bollian/tree-sitter-openscad#6]
This grammer has semi-colon listed as optional at the end of use/include. It isn't optional it simply isn't necessary at the end of use/include. 

`include_statement: $ => prec.left(seq(choice('use', 'include'), $.include_path, optional(';'))),`

A semi-colon at the end of use/include does compile but that is because `;` is a legal statement all by itself. So `use <whatever.scad>;` is actually two statements. The `use <whatever.scad>` is one, and then the `;` is another statement that just happens to be empty.

**Comment by Leathong** [comment]
https://github.com/openscad/openscad/blob/master/src/core/lexer.l

**Comment by Leathong** [comment]
https://github.com/openscad/openscad/blob/master/src/core/lexer.l
there is the lexer file of OpenSCAD, no semicolon at end of include statement

**Comment by bollian** [comment]
What I'm also learning here is that `use` is just a valid statement that can go anywhere, including inside a module definition.

**Comment by bollian** [comment]
I believe this issue is fixed by 64b8b43.
