### ISSUE TITLE
assert support is not  working correctly

### ISSUE THREAD

**Issue by Leathong** [bollian/tree-sitter-openscad#8]
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/24642875/197441406-62958fe3-1b81-4016-96a5-436a76ebd2f5.png">

**Comment by bollian** [comment]
I neglected to parse the message parameter, as well as the possibility of trailing parameters and 0 parameters. This should all be fixed as of 0.4.2 (a07497e).
